[project]
name = "mcp-crypto-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.66.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
    "python-dotenv>=1.0.0",
]
